# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.dev.cdwv.pl/cdwv/kubernetes-deployments/static-compiled-page
  tag: feature-gitlab-ci
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  track: stable
  additionalLabels: {}
service:
  name: web
  type: ClusterIP
  url: http://static-compiled-page.dev.cdwv.pl/
exampleEnvVariable: ""
