apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
  annotations:
{{- if eq (substr 0 5 .Values.service.url) "https" }}
    kubernetes.io/tls-acme: "true"
{{- end }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-snippet: |
      server_tokens off;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/custom-http-errors: "50x"
spec:
{{- if eq (substr 0 5 .Values.service.url) "https"}}
  tls:
  - hosts:
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ template "fullname" . }}-tls
{{- end }}
  rules:
  - host: {{ template "hostname" .Values.service.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: web-port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-refresh
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
  annotations:
{{- if eq (substr 0 5 .Values.service.url) "https" }}
    kubernetes.io/tls-acme: "true"
{{- end }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-snippet: |
      server_tokens off;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/custom-http-errors: "50x"

spec:
{{- if eq (substr 0 5 .Values.service.url) "https"}}
  tls:
  - hosts:
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ template "fullname" . }}-tls
{{- end }}
  rules:
  - host: {{ template "hostname" .Values.service.url }}
    http:
      paths:
      - path: /__refresh
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: web-port
