apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
    name: web-port
  selector:
    app: {{ template "appname" . }}
    tier: "web"

